import React from "react";

export default function Add({
  handleChange,
  handleSubmit,
  investmentName,
  agency,
  subagency,
  briefDescription,
  yearEstablished,
  fundingFY2008,
  fundingFY2009,
  fundingFY2010,
  missionSpecificOrGeneralStem,
  agencyOrMissionRelatedNeeds,
  primaryInvestmentObjective
}) {
  return (
    <div>
      <form onSubmit={handleSubmit}>
        <input
          name="investmentName"
          value={investmentName}
          onChange={handleChange}
          type="text"
          required
        />
        <input
          name="agency"
          value={agency}
          onChange={handleChange}
          type="text"
          required
        />
        <input
          name="subagency"
          value={subagency}
          onChange={handleChange}
          type="text"
          required
        />
        <input
          name="briefDescription"
          value={briefDescription}
          onChange={handleChange}
          type="textarea"
          required
        />
        <input
          name="yearEstablished"
          value={yearEstablished}
          onChange={handleChange}
          type="date"
          required
        />
        <input
          name="fundingFY2008"
          value={fundingFY2008}
          onChange={handleChange}
          type="number"
          step="0.01"
          required
        />
        <input
          name="fundingFY2009"
          value={fundingFY2009}
          onChange={handleChange}
          type="number"
          step="0.01"
          required
        />
        <input
          name="fundingFY2010"
          value={fundingFY2010}
          onChange={handleChange}
          type="number"
          step="0.01"
          required
        />
        <input
          name="missionSpecificOrGeneralStem"
          value={missionSpecificOrGeneralStem}
          onChange={handleChange}
          type="text"
          required
        />
        <input
          name="agencyOrMissionRelatedNeeds"
          value={agencyOrMissionRelatedNeeds}
          onChange={handleChange}
          type="text"
        />
        <input
          name="primaryInvestmentObjective"
          value={primaryInvestmentObjective}
          onChange={handleChange}
          type="textarea"
          required
        />
        <button type="submit">Add Fund</button>
      </form>
    </div>
  );
}
